### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by infinite111** [bihealth/vcfpy#125]
* vcfpy version: N/A
* Python version: 3.6.0
* Operating System: Windows 10
Anaconda Version: 4.3.1 (64 bit)

I am unable to install vcfpy onto multiple systems, is there an issue with anaconda or windows and this package?

What I Did

I have attempted installation across multiple systems, all which culminate into this issue.
![vcfpyissue](https://cloud.githubusercontent.com/assets/26745149/24414170/989e828a-13ab-11e7-880d-b9735a3606f0.PNG)

**Comment by holtgrewe** [comment]
Hi, thanks for your interest in vcfpy. Your problem is in vcfpy's dependency `pysam`. There is no precompiled version available, apparently, for your Python/OS combination...

Let me see whether I can whip up a [Bioconda](http://bioconda.github.io) package tomorrow.

**Comment by holtgrewe** [comment]
Ah, pysam only supports Linux and Mac Os X, as it seems. I think you're out of luck on Windows (probably generally true for many Bioinformatics tools).

I'd suggest installing Linux in a VM (e.g. Ubuntu 16.04 in Oracle VirtualBox).
