### ISSUE TITLE
VCF Writer seems not to write header

### ISSUE THREAD

**Issue by rvanheusden** [bihealth/vcfpy#132]
* vcfpy version: 0.12.1
* Python version: 3.7
* Operating System: macOS

When attempting to do a roundtrip with a reader and a writer, I run into an `IncorrectVCFFormat` exception complaining about the header line.

Here is where I create the writer (I'm writing to a buffer rather than a file):
```python
with io.StringIO() as vcf_stream:
    with vcfpy.Reader.from_path(self.template_vcf) as template_vcf_reader:
        vcf_writer = vcfpy.Writer.from_stream(vcf_stream, header=template_vcf_reader.header)

    ...
```

Then I do some subsequent `write_record` calls (which do not come from the template; the template VCF just contains headers).

Finally, I read the buffer with (effectively) `vcfpy.Reader.from_stream(vcf_stream)`

Unfortunately, this results in the aforementioned exception:
```
vcfpy.exceptions.IncorrectVCFFormat: Missing line starting with "#CHROM"
```

**Comment by rvanheusden** [comment]
Sorry, after looking into this more, I realized that this was actually an issue with how I was using StringIO. My apologies!

**Comment by holtgrewe** [comment]
@rvanheusden no problem, thanks for looking into this further.
