### ISSUE TITLE
Problem with colons when writing INFO field value strings

### ISSUE THREAD

**Issue by kathryn-beal** [bihealth/vcfpy#136]
* vcfpy version: 0.12.2
* Python version: 3.7
* Operating System: Ubuntu bionic

### Description

When writing the VCF record, the colon [:] is escaped to %3A in the INFO field value strings which is causing a problem for us. According to the VCF specification, colons are not excluded eg for v4.3,
8.  INFO — additional information:  (String, no semi-colons or equals-signs permitted; commas are permitted only as delimiters for lists of values; characters with special meaning can be encoded using the percent encoding, see Section 1.2; space characters are allowed)

Help with resolving this issue would be very much appreciated.

**Comment by holtgrewe** [comment]
Dear @kathryn-beal. Thank you for your report. Please give me a turnaround time of one week to deal with this.

**Comment by keiranmraine** [comment]
Is this likely to get fixed?

**Comment by holtgrewe** [comment]
Dear @keiranmraine and @kathryn-beal, I'm sorry for the long turnaround. Thanks for the reminder. Please checkout `v0.13.0` that I just tagged and uploaded to pypi.

**Comment by holtgrewe** [comment]
Please re-open if the problem persits.
