### ISSUE TITLE
FORMAT: list or tuple?

### ISSUE THREAD

**Issue by parlar** [bihealth/vcfpy#137]
* vcfpy version: 0.13.2
* Python version: 3.6
* Operating System: Centos 7

### Description

When record.FORMAT is empty it is a tuple but when a vcf containing calls and FORMAT columns is imported FORMAT it turns into a list.

 An empty FORMAT object cannot be filled using ```record.add_format()```. An exception is thrown: ```AttributeError: 'tuple' object has not attribute 'append' ```

if a key is to be added to an empty FORMAT using record.add_format(), it must first be converted into a list:

```
record.FORMAT = []
record.add_format('GT')
```

**Comment by holtgrewe** [comment]
Will be resolved by #140.
