### ISSUE TITLE
add FORMAT and calls to vcf?

### ISSUE THREAD

**Issue by parlar** [bihealth/vcfpy#138]
vcfpy version: 0.13.2
Python version: 3.6
Operating System: Centos 7

### Question

I would like to modify a vcf (from Lofreq) that does not contain FORMAT or call columns in order for it to be accepted by Picard within the bcbio-nextgen framework. 

I have tried like this but it does not work. Nothing comes out:

```
reader = vcfpy.Reader.from_path("/path/to/sample.vcf.gz")
reader.header.samples = vcfpy.SamplesInfos(names=['D20-XXX'], name_to_idx={'D20-XXX': 0})

writer = vcfpy.Writer.from_path('/dev/stdout', reader.header)

for rec in reader:
    data = {'GT': '1/1'}
    rec.calls.append(vcfpy.Call(sample=sample, data=data))
    rec.FORMAT = []
    rec.add_format('GT')
    writer.write_record(rec)
```

Is there some inherent limitation that prevents adding this info? I noticed a caveat that the FORMAT field cannot be altered after modifying the SamplesInfos object.

Incidently, I have also noticed that data objects in the call instances are dicts and not ordered dicts, as the documentation says. Perhaps a remnant from earlier times?

**Comment by holtgrewe** [comment]
Hi, I'll look into this.

Actually, since Python 3.6 or 3.7 dicts behave like ordered dicts :) vcfpy switches types as appropriate.

**Comment by holtgrewe** [comment]
Hi, look into the test added in #141 for an example. I will create a new release soon that includes this patch.

**Comment by holtgrewe** [comment]
OK, v0.13.3 is out on vcfpy. I guess that bioconda bot will pull this to bioconda really soon now.
