### ISSUE TITLE
Unknown Filter `PASS`

### ISSUE THREAD

**Issue by lczech** [bihealth/vcfpy#142]
* vcfpy version: 0.11.2
* Python version: 3.7
* Operating System: Ubuntu 20.04

### Description

Parsing a file.

### What I Did

Copy/pasted the code from https://vcfpy.readthedocs.io/en/stable/examples.html#reading-vcf-files

### What I get

```
.../vcfpy/parser.py:495: UnknownFilter: Filter not found in header: PASS; problem in FILTER column
```

I think that `PASS` is simply the VCF way of saying that all filters passed, so I think this should not be considered an unknown filter.

**Comment by holtgrewe** [comment]
I agree and

https://github.com/bihealth/vcfpy/blob/master/vcfpy/parser.py#L494

also agrees. Could you share a minimal version of the problematic VCF file?

Thanks!

**Comment by lczech** [comment]
Sure, this one: 
[all.vcf.gz](https://github.com/bihealth/vcfpy/files/6216396/all.vcf.gz)

with the example code that I linked above.

**Comment by holtgrewe** [comment]
Hm, this has been fixed since

https://github.com/bihealth/vcfpy/commit/7388efad0289065f08d5eb57d1e529b075a7ad8d

so I suggest upgrading the library.

**Comment by lczech** [comment]
Ah, I see. I have been using v0.11.2 from https://anaconda.org/bioconda/vcfpy, as this seemed to be the latest linux version there - but apparently, the "noarch" version 0.13.3 also works - is that a platform independent version then?! Anyway, works now. Thank for the feedback!

**Comment by holtgrewe** [comment]
Hm, I guess this is related to Bioconda build system changes...
